// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skgwdaszyvkwpfmiercp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrZ3dkYXN6eXZrd3BmbWllcmNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3ODE3MDcsImV4cCI6MjA3NzM1NzcwN30.bozYqcsTGbWiyw8dmSj4NqNHN0xbm0LgznRzrGhL3wg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});